// frontend/src/components/layout/Search.vue
<template>
	<div class="z-40">
		<form
			@submit.prevent="searchCars"
			class="bg-opacity-60 transition-opacity opacity-80 border py-4 rounded-full flex flex-col justify-center items-center lg:mx-auto lg:grid lg:grid-cols-5 lg:w-9/12 lg:gap-2 lg:px-4 lg:py-2 w-full lg:my-8"
		>
			<!-- Property Type -->
			<div class="flex flex-col px-4">
				<select
					v-model="type"
					class="border rounded-full bg-white px-1 py-2 md:py-3 md:text-lg lg:px-2 lg:py-3 lg:space-y-4"
				>
					<option value="">Looking For</option>
					<option value="type1">Apartment</option>
					<option value="type1">Villa</option>
					<option value="type1">Condo</option>
					<option value="type1">Homes</option>
				</select>
			</div>
			<!-- Location Filter -->
			<div class="flex flex-col px-4">
				<select
					v-model="location"
					class="border rounded-full bg-white px-1 py-2 md:py-3 md:text-lg lg:px-2 lg:py-3"
				>
					<option value="">Any Location</option>
					<option value="location2">Nairobi</option>
					<option value="location2">Mombasa</option>
					<option value="location1">Nakuru</option>
				</select>
			</div>

			<!-- Property size Filter -->
			<div class="flex flex-col px-4">
				<select
					v-model="size"
					class="border rounded-full w-full bg-white px-1 py-2 md:py-3 lg:px-2 lg:py-3"
				>
					<option value="">Apartment</option>
					<option value="small">Studio</option>
					<option value="medium">1 Bedroom</option>
					<option value="large">2 Bedroom</option>
					<option value="large">3 Bedroom</option>
					<option value="large">4 Bedroom</option>
					<option value="large">5 Bedroom</option>
					<option value="large">6 Bedroom</option>
				</select>
			</div>

			<!-- Price Filter -->
			<div class="flex flex-col px-4">
				<input
					v-model="price"
					class="px-3 py-2 border rounded-full bg-white text-lg md:px-4"
					placeholder="ksh"
					type="number"
					min="0"
					step="10"
				/>
			</div>

			<button
				type="submit"
				class="text-white rounded-full flex bg-blue-600 py-2 font-bold md:py-1 lg:justify-center lg:items-center lg:text-xl h-16 lg:space-x-2"
			>
				<span class="material-symbols-outlined text-3xl"> search </span
				><span class="text-2xl">Search</span>
			</button>
		</form>
	</div>
</template>

<script setup>
import { ref } from "vue";

const type = ref("");
const location = ref("");
const size = ref("");
const price = ref(null);

const searchCars = () => {
	// Handle the search functionality here, including the selected options.
};
</script>

<style scoped>
.hero {
	/* Add your Hero section styles here */
}
</style>

// frontend/src/components/Search.jsx
import React from "react";

function Search() {
  return (
    <div className="p-4 ">
      <div className="max-w-xl mx-auto  border-2 rounded">
        <div className="flex items-center space-x-1">
          <div className="relative flex-grow">
            <div className="flex items-center">
              <select
                id="location"
                name="location"
                className="appearance-none bg-white border border-gray-300 hover:border-gray-500 px-4 py-1 pr-8 rounded-l shadow leading-tight focus:outline-none focus:shadow-outline"
              >
                <option value="">Location</option>
                <option value="location1">Nairobi</option>
                <option value="location2"> Nakuru</option>
              </select>

              <input
                type="text"
                id="price"
                name="price"
                placeholder="Price"
                className="flex-grow bg-white border border-gray-300 hover:border-gray-500 px-2 py-1 rounded-r shadow  focus:outline-none focus:shadow-outline"
              />
            </div>
          </div>

          <div className="relative">
            <select
              id="size"
              name="size"
              className="block appearance-none w-full bg-white border border-gray-300 hover:border-gray-500 px-4 py-1 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline"
            >
              <option value=""> Size</option>
              <option value="size1">1 Bedroom</option>
              <option value="size2"> 2 Bedroom</option>
            </select>
          </div>

          <button
            type="button"
            className="bg-blue-500 text-white px-4 py-1 rounded hover:bg-blue-600 focus:outline-none focus:shadow-outline"
          >
            Search
          </button>
        </div>
      </div>
    </div>
  );
}

export default Search;
