// frontend/src/components/SearchComponent.tsx
import React, { useState } from "react";

const SearchComponent = () => {
  const [category, setCategory] = useState("");
  const [city, setCity] = useState("");
  const [area, setArea] = useState("");
  const [rooms, setRooms] = useState("");
  const [minPrice, setMinPrice] = useState("");
  const [maxPrice, setMaxPrice] = useState("");

  const handleMinPriceChange = (e) => setMinPrice(e.target.value);
  const handleMaxPriceChange = (e) => setMaxPrice(e.target.value);

  const handleSearch = () => {
    console.log({ category, city, area, rooms, minPrice, maxPrice });
  };

  return (
    <div className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col text-sm ">
      <div className="flex">
        <div className="mb-4 md:mr-2 md:mb-0">
          <label
            className="block mb-2 text-sm font-bold text-gray-700"
            htmlFor="category"
          >
            Categories
          </label>
          <select
            id="category"
            className="shadow border rounded w-full py-2 px-3 text-gray-700"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          >
            <option value="">PROPERTY TYPE</option>
            <option value="Residential">Residential</option>
            <option value="Commercial">Commercial</option>
            <option value="Villa">Villa</option>
            <option value="Apartment">Apartment</option>
          </select>
        </div>
        <div className="mb-4 md:mr-2 md:mb-0">
          <label
            className="block mb-2 text-sm font-bold text-gray-700"
            htmlFor="city"
          >
            City
          </label>
          <select
            id="city"
            className="shadow border rounded w-full py-2 px-3 text-gray-700"
            value={city}
            onChange={(e) => setCity(e.target.value)}
          >
            <option value="">Property City</option>
            <option value="Nakuru">Nakuru</option>
            <option value="Nairobi">Nairobi</option>
            <option value="Mombasa">Mombasa</option>
            <option value="Machakos">Machakos</option>
          </select>
        </div>
        <div className="mb-4 md:mr-2 md:mb-0">
          <label
            className="block mb-2 text-sm font-bold text-gray-700"
            htmlFor="area"
          >
            Area
          </label>
          <select
            id="area"
            className="shadow border rounded w-full py-2 px-3 text-gray-700"
            value={area}
            onChange={(e) => setArea(e.target.value)}
          >
            <option value="">Property Area</option>
            <option value="Ngong">Ngong</option>
            <option value="Kitengela">Kitengela</option>
            <option value="Wetlands">Wetlands</option>
            <option value="Kileleshwa">Kileleshwa</option>
          </select>
        </div>
        <div className="mb-4 md:mr-2 md:mb-0">
          <label
            className="block mb-2 text-sm font-bold text-gray-700"
            htmlFor="rooms"
          >
            Rooms
          </label>
          <select
            id="rooms"
            className="shadow border rounded w-full py-2 px-3 text-gray-700"
            value={rooms}
            onChange={(e) => setRooms(e.target.value)}
          >
            <option value="">Rooms Number</option>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
          </select>
        </div>
      </div>
      <div className="flex space-x-4 mt-2">
        <input
          type="number"
          className="border px-2 py-1"
          placeholder="Min Price"
          value={minPrice}
          onChange={handleMinPriceChange}
          aria-label="Minimum Price"
        />
        <input
          type="number"
          className="border px-2 py-1"
          placeholder="Max Price"
          value={maxPrice}
          onChange={handleMaxPriceChange}
          aria-label="Maximum Price"
        />
        <button
          className="w-full shadow bg-blue-500 hover:bg-blue-400 focus:shadow-outline focus:outline-none text-white font-bold py-1 text-sm px-6 rounded"
          type="button "
          onClick={handleSearch}
        >
          Search
        </button>
      </div>
    </div>
  );
};

// Optional: Add PropTypes
// SearchComponent.propTypes = {
//   // Define PropTypes here if needed
// };

export default SearchComponent;

// frontend/src/components/layout/Search.vue
<template>
	<div class="z-40">
		<form
			@submit.prevent="searchCars"
			class="bg-opacity-60 bg-black transition-opacity opacity-80 border py-4 rounded-lg flex flex-col lg:mx-auto lg:grid lg:grid-cols-5 lg:w-9/12 lg:gap-4 lg:px-2 lg:py-4 w-full"
		>
			<!-- Property Type -->
			<div class="mb-4 flex flex-col px-4">
				<label class="text-xl text-white">LOOKING FOR</label>
				<select
					v-model="type"
					class="border rounded bg-white px-1 py-2 md:py-3 md:text-lg lg:px-2 lg:py-3 lg:space-y-4"
				>
					<option value="">Property Type</option>
					<option value="location1">Apartment</option>
					<option value="location2">Villa</option>
					<option value="location2">Condo</option>
					<option value="location2">Bungalow</option>
				</select>
			</div>
			<!-- Location Filter -->
			<div class="mb-4 flex flex-col px-4">
				<label class="text-xl text-white">LOCATION</label>
				<select
					v-model="location"
					class="border rounded bg-white px-1 py-2 md:py-3 md:text-lg lg:px-2 lg:py-3"
				>
					<option value="">Any Location</option>
					<option value="location2">Nairobi</option>
					<option value="location2">Mombasa</option>
					<option value="location1">Nakuru</option>
				</select>
			</div>

			<!-- Property size Filter -->
			<div class="mb-4 flex flex-col px-4">
				<label class="text-xl text-white md:text-lg">PROPERTY SIZE</label>
				<select
					v-model="size"
					class="border rounded w-full bg-white px-1 py-2 md:py-3 lg:px-2 lg:py-3"
				>
					<option value="">Apartment</option>
					<option value="small">Studio</option>
					<option value="medium">1 Bedroom</option>
					<option value="large">2 Bedroom</option>
					<option value="large">3 Bedroom</option>
					<option value="large">4 Bedroom</option>
					<option value="large">5 Bedroom</option>
					<option value="large">6 Bedroom</option>
				</select>
			</div>

			<!-- Price Filter -->
			<div class="mb-4 flex flex-col px-4">
				<label class="text-xl text-white">YOUR BUDGET</label>
				<input
					v-model="price"
					class="px-3 py-2 border rounded bg-white text-lg md:px-4"
					placeholder="ksh"
					type="number"
					min="0"
					step="10"
				/>
			</div>

			<button
				type="submit"
				class="text-white rounded bg-blue-600 mx-4 my-2 py-2 font-bold md:py-3 lg:my-5 lg:mx-4 lg:text-xl"
			>
				SEARCH
			</button>
		</form>
	</div>
</template>

<script setup>
import { ref } from "vue";

const type = ref("");
const location = ref("");
const size = ref("");
const price = ref(null);

const searchCars = () => {
	// Handle the search functionality here, including the selected options.
};
</script>

<style scoped>
.hero {
	/* Add your Hero section styles here */
}
</style>
