// frontend/src/components/layout/Header.vue
<template>
	<div class="bg-[#061158] top-0 sticky z-[100]">
		<!-- Desktop Navbar -->
		<div
			class="px-4 sm:px-6 hidden lg:flex justify-between lg:items-center py-4 border-b-2 border-white"
		>
			<router-link class="text-white text-2xl" to="/"> Flasky </router-link>

			<ul class="space-x-16 lg:flex">
				<li><router-link to="/" class="text-white">Home</router-link></li>
				<li>
					<router-link
						to="/properties"
						@click="toggleMobileSidebar"
						class="text-white"
						>Properties</router-link
					>
				</li>

				<li>
					<router-link
						to="/profile"
						@click="toggleMobileSidebar"
						class="text-white"
						>Profile</router-link
					>
				</li>
				<li>
					<router-link
						to="/logout"
						@click="toggleMobileSidebar"
						class="text-white"
					>
						Logout
					</router-link>
				</li>
			</ul>
		</div>

		<!-- Mobile Navbar (sidebar) -->
		<div
			class="lg:hidden fixed w-full h-20 z-[100] shadow-xl transition-transform ease-in-out duration-300 bg-[#061158]"
		>
			<div class="max-w-7xl lg:px-8 py-4">
				<div class="flex items-center justify-between">
					<router-link to="/">
						<span class="text-white text-xl ml-4"> Flasky</span>
					</router-link>
					<button
						@click="toggleMobileSidebar"
						class="text-white mr-2 text-2xl lg:hidden"
					>
						{{ mobileSidebarOpen ? "✕" : "☰" }}
					</button>
				</div>
				<div name="slide " class="w-9/12 ml-auto left-0">
					<div
						v-if="mobileSidebarOpen"
						class="bg-[#061158] text-white mt-4 p-4 rounded-lg opacity-80 h-screen"
					>
						<div class="space-y-12 text-xl ml-4">
							<div class="font-bold text-lg">
								<router-link to="/" @click="toggleMobileSidebar">
									Home</router-link
								>
							</div>
							<div class="font-bold text-lg">
								<router-link to="/rentals" @click="toggleMobileSidebar">
									<span>For rent</span>
								</router-link>
							</div>
							<div class="font-bold text-lg">
								<router-link to="/sale" @click="toggleMobileSidebar">
									<span>For sale</span>
								</router-link>
							</div>
							<div class="font-bold text-lg">
								<router-link to="/profile" @click="toggleMobileSidebar">
									Profile</router-link
								>
							</div>
							<ul class="space-y-4">
								<div class="font-bold text-xl my-5">Settings and legal</div>
								<li class="font-light">About flasky.com</li>
								<li class="font-light">Terms and conditions</li>
								<li class="font-light">Privacy and cookies</li>
							</ul>
							<div>
								<router-link to="/logout" @click="toggleMobileSidebar">
									Logout</router-link
								>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script setup>
import { ref } from "vue";

const mobileSidebarOpen = ref(false);

const toggleMobileSidebar = () => {
	mobileSidebarOpen.value = !mobileSidebarOpen.value;
};
</script>

<style>
.slide-enter-active,
.slide-leave-active {
	transition: transform 0.3s;
}
.slide-enter,
.slide-leave-to {
	transform: translateX(100%);
}
</style>

// frontend/src/layout/Header.tsx
import React, { useState } from "react";
import { MdMenu } from "react-icons/md";
import { CgProfile } from "react-icons/cg";
import { Link } from "react-router-dom";

const Header: React.FC = () => {
  const [isPropertiesDropdownOpen, setIsPropertiesDropdownOpen] =
    useState(false);
  const [isMenuDropdownOpen, setIsMenuDropdownOpen] = useState(false);

  return (
    <nav className="max-w-md:hidden  w-full py-4 bg-white fixed z-20 top-0 shadow">
      <div className="flex items-center px-3">
        <div className="mr-12 p-1"><Link to='/'>logo</Link></div>
        <div className="container  flex items-center justify-end">
          <div className="px-4 cursor-pointer">
            <Link to="/">Home</Link>
          </div>
          <div className="relative px-4">
            <button
              onClick={() =>
                setIsPropertiesDropdownOpen(!isPropertiesDropdownOpen)
              }
              className="cursor-pointer"
            >
              Properties
            </button>
            {isPropertiesDropdownOpen && (
              <div className="absolute right-0 w-32 py-2 mt-2 bg-white rounded-md shadow-xl z-10">
                <a
                  href="/for-sale"
                  className="block px-4 py-2 text-sm text-slate-800 hover:bg-gray-100"
                >
                  For Sale
                </a>
                <a
                  href="/for-rent"
                  className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  For Rent
                </a>
              </div>
            )}
          </div>
          <div className="relative px-4">
            <button
              onClick={() => setIsMenuDropdownOpen(!isMenuDropdownOpen)}
              className="cursor-pointer flex space-x-1 items-center"
            >
              <MdMenu className="text-xl" />
              <CgProfile className="text-2xl" />
            </button>
            {isMenuDropdownOpen && (
              <div className="absolute right-0 w-32 py-2 mt-2 bg-white rounded-md shadow-xl z-10">
                <a
                  href="/profile"
                  className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  Profile
                </a>
                <a
                  href="/settings"
                  className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  Settings
                </a>
                <a
                  href="/logout"
                  className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100"
                >
                  Logout
                </a>
              </div>
            )}
          </div>
          <div>
            <button className=" bg-blue-500 text-white py-2 px-3 text-sm font-bold rounded">
              <Link to="/create-listing"> Add Listing</Link>
            </button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Header;
